### ISSUE TITLE
Polylines error happening with version 0.6.0+1

### ISSUE THREAD

**Issue by danfixeads** [johnpryan/flutter_map#311]
Hello

Whenever I try to add PolylineLayerOptions as a layer, the following error happens:

`Another exception was thrown: type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'`

It seems to be caused by the PolylineLayer _build method (line 56).

I checked the example project, and it's also happening there.
![Simulator Screen Shot - iPhone 6 - 2019-06-07 at 15 22 37](https://user-images.githubusercontent.com/7807669/59107043-19785080-8938-11e9-8bb2-7d640b967578.png)

**Comment by danfixeads** [comment]
Hello @johnpryan, any updates?  Perhaps you can consider looking at the https://github.com/johnpryan/flutter_map/pull/328 PR to see if it will resolve this issue.

**Comment by mulderpf** [comment]
That PR did not fix the issue for me.  My app is now completely broken due to this (Flutter Stable is being updated to 1.7.8 today and 0.5.x and 0.6.x are both creating this issue).

**Comment by johnpryan** [comment]
I see - it sounds like you might be using flutter's `dev` channel, not `stable`. flutter_map's dev branch is published to Pub under  0.6.x

**Comment by lsaudon** [comment]
The error is present on the `stable` version (1.7.8+hotfix.2)

**Comment by ehhc** [comment]
Are there any news on this? I'm using flutter 1.7.8+hotfix.3 and flutter_map: 0.6.1+2

**Comment by mulderpf** [comment]
No, I tried it with both beta and stable, definitely did not work.  Stable today is where beta was a few days ago any way (1.7.8+hotfix.x).

**Comment by fre391** [comment]
same here, also newest version 0.6.1+2

**Comment by johnpryan** [comment]
`flutter_map` `0.5.6` is compatible with flutter's stable branch now. `flutter_map` `0.6.x` is only compatible with flutter's master channel (and subject to break)

**Comment by ehhc** [comment]
Is it just me or does the error mentioned above also happens with the `0.5.6` version and the current stable version of flutter?!

**Comment by mulderpf** [comment]
I validated this and 0.5.6 definitely works properly with 1.7.8+hotfix.3 (I just published my app out to production once I got it working properly - truth be told, when I was trying it out 5 days ago, I couldn't get the combination to work, so caching might have been at play).

**Comment by ehhc** [comment]
Hi @mulderpf, i still have the same problem as before:

I'm using Flutter ` v1.7.8+hotfix.3` and `flutter_map: '^0.5.6'`

My code is like the following:
```
GridTile(
            child: FlutterMap(
              options: MapOptions(
                  center: LatLng(lastPosition.lat, lastPosition.lon),
                  zoom: 16.0,
                  maxZoom: 19),
              layers: [
                TileLayerOptions(
                    urlTemplate:
                        "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                    subdomains: ['a', 'b', 'c']),
                PolylineLayerOptions(
                  polylines: [
                    Polyline(
                        points: historicPositions.map((p) => LatLng(p.lat, p.lon)).toList(),
                        strokeWidth: 4.0,
                        color: Colors.red.shade800),
                  ],
                ),
                MarkerLayerOptions(
                    markers: [Marker(
                            width: 50,
                            height: 70,
                            point: LatLng(lastPosition.lat, lastPosition.lon),
                            builder: (ctx) => MarkerWithTimeStamp(
                                icon: Icon(markerIcon, size: 40, color: Colors.red.shade800),
                                timeStamp: lastPosition.timeStamp),
                          )]
                ),
              ],
            ),
            footer: Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: <Widget>[
                InkWell(
                    child: Text(
                      "© OpenStreetMap contributors",
                      style: TextStyle(color: Colors.blue, background: Paint()..color = Colors.white.withAlpha(200)),
                    ),
                    onTap: () => launch('https://www.openstreetmap.org/copyright'))
              ],
            ),
          ),
```

And i get the following error message. 
Any ideas how to solve that?

```
I/flutter ( 6454): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6454): The following assertion was thrown building LayoutBuilder:
I/flutter ( 6454): type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'
I/flutter ( 6454): 
I/flutter ( 6454): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6454): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6454): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6454):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 6454): 
I/flutter ( 6454): When the exception was thrown, this was the stack:
I/flutter ( 6454): #0      PolylineLayer._build (package:flutter_map/src/layer/polyline_layer.dart:56:15)
I/flutter ( 6454): #1      PolylineLayer.build.<anonymous closure> (package:flutter_map/src/layer/polyline_layer.dart:49:16)
I/flutter ( 6454): #2      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:113:26)
I/flutter ( 6454): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 6454): #4      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:109:11)
I/flutter ( 6454): #5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1715:58)
I/flutter ( 6454): #6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter ( 6454): #7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
I/flutter ( 6454): #8      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:5)
I/flutter ( 6454): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #10     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 6454): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #12     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 6454): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #22     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:209:13)
I/flutter ( 6454): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #24     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:549:15)
I/flutter ( 6454): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #26     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 6454): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #28     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 6454): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #34     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:549:15)
I/flutter ( 6454): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #36     RenderAnimatedSize.performLayout (package:flutter/src/rendering/animated_size.dart:182:11)
I/flutter ( 6454): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #39     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 6454): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #41     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter ( 6454): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #50     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 6454): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #52     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 6454): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #56     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter ( 6454): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #58     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 6454): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #60     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 6454): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #62     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:497:13)
I/flutter ( 6454): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #84     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #86     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 6454): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #88     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:209:13)
I/flutter ( 6454): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 6454): #90     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 6454): #91     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 6454): #92     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 6454): #93     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 6454): #94     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 6454): #95     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 6454): #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 6454): #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 6454): #98     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 6454): #99     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 6454): #100    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 6454): #101    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 6454): #105    _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 6454): #106    _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 6454): (elided 3 frames from package dart:async)
I/flutter ( 6454): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by edufolly** [comment]
A great workaround is trying to use the dev branch in pubspec.yaml

```yaml
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: dev
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.2-pre.126, on Mac OS X 10.14.5 18F132, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (3 available)
```

**Comment by fabriciokjc** [comment]
I have the same problem

**Comment by fabriciokjc** [comment]
> A great workaround is trying to use the dev branch in pubspec.yaml
> 
> ```yaml
>   flutter_map:
>     git:
>       url: git://github.com/johnpryan/flutter_map.git
>       ref: dev
> ```
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v1.8.2-pre.126, on Mac OS X 10.14.5 18F132, locale pt-BR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.4)
> [✓] VS Code (version 1.36.1)
> [✓] Connected device (3 available)
> ```

it worked for me

**Comment by edufolly** [comment]
I changed to the master branch and everything works great and using ```path_provider: ^1.1.0```.
